name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Deploy project
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }} # IP address of the remote server
          key: ${{ secrets.SSH_KEY }} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server
     
          script: |
            echo 'Deployment successful to digital ocean' 
